CREATE TABLE endereco
(
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    logradouro VARCHAR(255),
    numero     INT,
    localidade VARCHAR(255),
    uf         VARCHAR(255),
    estado     VARCHAR(255),
    cep        VARCHAR(255),
    CONSTRAINT pk_endereco PRIMARY KEY (id)
);