CREATE TABLE filial
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cnpj VARCHAR(30),
    endereco_id INT,
    fk_mercado  INT                                  NOT NULL,
    CONSTRAINT pk_filial PRIMARY KEY (id)
);

ALTER TABLE filial
    ADD CONSTRAINT FK_FILIAL_ON_ENDERECO FOREIGN KEY (endereco_id) REFERENCES endereco (id);

ALTER TABLE filial
    ADD CONSTRAINT FK_MERCADO_FILIAL FOREIGN KEY (fk_mercado) REFERENCES mercado (id);