CREATE TABLE produto_filial
(
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    preco      DOUBLE PRECISION,
    situacao   VARCHAR(255),
    fk_produto INT                                  NOT NULL,
    fk_filial  INT                                  NOT NULL,
    CONSTRAINT pk_produto_filial PRIMARY KEY (id)
);

ALTER TABLE produto_filial
    ADD CONSTRAINT FK_PRODUTO_FILIAL_FILIAL FOREIGN KEY (fk_filial) REFERENCES filial (id);

ALTER TABLE produto_filial
    ADD CONSTRAINT FK_PRODUTO_FILIAL_PRODUTO FOREIGN KEY (fk_produto) REFERENCES produto (id);