CREATE TABLE estoque
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade         DOUBLE PRECISION,
    ultima_atualizacao TIMESTAMP,
    fk_filial          INT                                  NOT NULL,
    fk_produto_filial  INT                                  NOT NULL,
    CONSTRAINT pk_estoque PRIMARY KEY (id)
);

ALTER TABLE estoque
    ADD CONSTRAINT uc_estoque_fk_produto_filial UNIQUE (fk_produto_filial);

ALTER TABLE estoque
    ADD CONSTRAINT FK_FILIAL_ESTOQUE FOREIGN KEY (fk_filial) REFERENCES filial (id);

ALTER TABLE estoque
    ADD CONSTRAINT FK_PRODUTO_FILIAL_ESTOQUE FOREIGN KEY (fk_produto_filial) REFERENCES produto_filial (id);