CREATE TABLE venda
(
    id             INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valor          DOUBLE PRECISION,
    data_venda     TIMESTAMP,
    tipo_pagamento VARCHAR(255),
    endereco_id    INT,
    usuario_id     VARCHAR(255),
    CONSTRAINT pk_venda PRIMARY KEY (id)
);

ALTER TABLE venda
    ADD CONSTRAINT FK_VENDA_ON_ENDERECO FOREIGN KEY (endereco_id) REFERENCES endereco (id);

ALTER TABLE venda
    ADD CONSTRAINT FK_VENDA_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);