CREATE TABLE estoque
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade         DOUBLE PRECISION,
    ultima_atualizacao TIMESTAMP,
    fk_produto         INT                                  NOT NULL,
    CONSTRAINT pk_estoque PRIMARY KEY (id)
);

ALTER TABLE estoque
    ADD CONSTRAINT uc_estoque_fk_produto UNIQUE (fk_produto);

ALTER TABLE estoque
    ADD CONSTRAINT FK_PRODUTO_ESTOQUE FOREIGN KEY (fk_produto) REFERENCES produto (id);