CREATE TABLE produto
(
    id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(255),
    marca        VARCHAR(255),
    descricao    VARCHAR(255),
    tipo_medida  VARCHAR(255),
    fk_categoria INT                                  NOT NULL,
    CONSTRAINT pk_produto PRIMARY KEY (id)
);

ALTER TABLE produto
    ADD CONSTRAINT FK_CATEGORIA_USUARIO FOREIGN KEY (fk_categoria) REFERENCES categoria (id);