CREATE TABLE produto_venda
(
    id                INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade        DOUBLE PRECISION,
    subtotal          DOUBLE PRECISION,
    data_venda        TIMESTAMP,
    fk_produto_filial INT                                  NOT NULL,
    fk_venda          INT                                  NOT NULL,
    CONSTRAINT pk_produtovenda PRIMARY KEY (id)
);

ALTER TABLE produto_venda
    ADD CONSTRAINT FK_PRODUTO_FILIAL_PRODUTO_VENDIDO FOREIGN KEY (fk_produto_filial) REFERENCES produto_filial (id);

ALTER TABLE produto_venda
    ADD CONSTRAINT FK_VENDA_PRODUTO_VENDIDO FOREIGN KEY (fk_venda) REFERENCES venda (id);