CREATE TABLE entrega
(
    id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cliente_nome VARCHAR(255),
    fk_endereco  INT                                  NOT NULL,
    fk_venda     INT                                  NOT NULL,
    CONSTRAINT pk_entrega PRIMARY KEY (id)
);

ALTER TABLE entrega
    ADD CONSTRAINT uc_entrega_fk_venda UNIQUE (fk_venda);

ALTER TABLE entrega
    ADD CONSTRAINT FK_ENDERECO_ENTREGA FOREIGN KEY (fk_endereco) REFERENCES endereco (id);

ALTER TABLE entrega
    ADD CONSTRAINT FK_VENDA_ENTREGA FOREIGN KEY (fk_venda) REFERENCES venda (id);